name: Test

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  test-71:
    name: PHP 7.1
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Alpine 3.7
        run: make test-image IMAGE="php:7.1-fpm-alpine3.7" DOCKERFILE="alpine"

      - name: Alpine 3.8
        run: make test-image IMAGE="php:7.1-fpm-alpine3.8" DOCKERFILE="alpine"

      - name: Stretch
        run: make test-image IMAGE="php:7.1-fpm-stretch" DOCKERFILE="stretch"
