name: Test

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - run: make lint

  test-71:
    runs-on: ubuntu-latest
    needs: lint
    steps:

      - uses: actions/checkout@v2
      - run: make test-image IMAGE="php:7.1-fpm-alpine3.7" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.1-fpm-alpine3.8" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.1-fpm-alpine3.9" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.1-fpm-alpine3.10" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.1-fpm-stretch" DOCKERFILE="stretch"
      - run: make test-image IMAGE="php:7.1-fpm-buster" DOCKERFILE="buster"

  test-72:
    runs-on: ubuntu-latest
    needs: lint
    steps:

      - uses: actions/checkout@v2
      - run: make test-image IMAGE="php:7.2-fpm-alpine3.7" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.2-fpm-alpine3.8" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.2-fpm-alpine3.9" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.2-fpm-alpine3.10" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.2-fpm-alpine3.11" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.2-fpm-alpine3.12" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.2-fpm-stretch" DOCKERFILE="stretch"
      - run: make test-image IMAGE="php:7.2-fpm-buster" DOCKERFILE="buster"

  test-73:
    runs-on: ubuntu-latest
    needs: lint
    steps:

      - uses: actions/checkout@v2
      - run: make test-image IMAGE="php:7.3-fpm-alpine3.8" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.3-fpm-alpine3.9" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.3-fpm-alpine3.10" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.3-fpm-alpine3.11" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.3-fpm-alpine3.12" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.3-fpm-alpine3.13" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.3-fpm-alpine3.14" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.3-fpm-alpine3.15" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.3-fpm-stretch" DOCKERFILE="stretch"
      - run: make test-image IMAGE="php:7.3-fpm-buster" DOCKERFILE="buster"

  test-74:
    runs-on: ubuntu-latest
    needs: lint
    steps:

      - uses: actions/checkout@v2
      - run: make test-image IMAGE="php:7.4-fpm-alpine3.10" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.4-fpm-alpine3.11" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.4-fpm-alpine3.12" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.4-fpm-alpine3.13" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.4-fpm-alpine3.14" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.4-fpm-alpine3.15" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:7.4-fpm-buster" DOCKERFILE="buster"

  test-80:
    runs-on: ubuntu-latest
    needs: lint
    steps:

      - uses: actions/checkout@v2
      - run: make test-image IMAGE="php:8.0-fpm-alpine3.12" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:8.0-fpm-alpine3.13" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:8.0-fpm-alpine3.14" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:8.0-fpm-alpine3.15" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:8.0-fpm-buster" DOCKERFILE="buster"

  test-81:
    runs-on: ubuntu-latest
    needs: lint
    steps:

      - uses: actions/checkout@v2
      - run: make test-image IMAGE="php:8.1-fpm-alpine3.14" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:8.1-fpm-alpine3.15" DOCKERFILE="alpine"
      - run: make test-image IMAGE="php:8.1-fpm-buster" DOCKERFILE="buster"
